name: 'Sentiment Analysis Action'
description: 'Analyzes text for sentiment and give a confidence score for positive, neutral and negative'
author: rob-derosa@github.com
branding:
  icon: bar-chart-2
  color: green
inputs:
  azure-cognitive-subscription-key:
    required: true
    description: 'Azure Cognitive Services resource key found in in the Azure Portal'
  azure-cognitive-endpoint:
    required: true
    description: 'Azure Cognitive Services endpoint found in in the Azure Portal'
  text-to-analyze:
    required: true
    description: 'The text to analyze for sentiment'
  text-language:
    required: true
    description: 'The language of the text to analyze for sentiment'
outputs:
  positive:
    description: 'Overall confidence score of positivity in the text'
  neutral:
    description: 'Overall confidence score of neutrality in the text'
  negative:
    description: 'Overall confidence score of negativity in the text'
  results:
    description: 'JSON payload of with deeper, per-sentence analysis'
runs:
  using: 'node12'
  main: 'dist/index.js'