name: 'analyze-sentiment'
on:
  issues:
    types:
      - opened
      - edited
  issue_comment:
    types:
      - created
      - edited
  pull_request:
    types:
      - opened
      - edited
  pull_request_review_comment:
    types:
      - created
      - edited
jobs:
  analyze-sentiment:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: step1
        name: "Run Sentiment Analysis"
        with:
          azureCognitiveSubscriptionKey: ${{ secrets.AZURE_COGNITIVE_SUBSCRIPTION_KEY }}
          azureCognitiveEndpoint: ${{ secrets.AZURE_COGNITIVE_ENDPOINT }}
          textToAnalyze: ${{ github.event.comment.body }}
          textLanguage: "en"
      - name: Dump output
        run: echo ${{ toJson(steps.step1.outputs) }}
  